# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost/gatewayDb?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Logging Configuration
logging:
  level:
    org:
      springframework: INFO
      hibernate: ERROR

server:
  port: 8300
