# Database Configuration
spring:
  config:
    import: setting.yml
  datasource:
    url: jdbc:mysql://localhost/${DB_DATABASE}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Logging Configuration
logging:
  level:
    org:
      springframework: INFO
      hibernate: ERROR

server:
  port: 8300
